# Databricks notebook source
# MAGIC %md
# MAGIC # Install Dependencies

# COMMAND ----------

# DBTITLE 1,Databricks RAG Studio Installer
# MAGIC %run ../wheel_installer

# COMMAND ----------

dbutils.library.restartPython() 

# COMMAND ----------

# MAGIC %md
# MAGIC # Imports

# COMMAND ----------

import json
import os

import mlflow
from databricks import rag, rag_eval, rag_studio

import html

mlflow.set_registry_uri('databricks-uc')

### START: Ignore this code, temporary workarounds given the Private Preview state of the product
from mlflow.utils import databricks_utils as du
os.environ['MLFLOW_ENABLE_ARTIFACTS_PROGRESS_BAR'] = "false"

def parse_deployment_info(deployment_info):
  browser_url = du.get_browser_hostname()
  message = f"""Deployment of {deployment_info.model_name} version {deployment_info.model_version} initiated.  This can take up to 15 minutes and the Review App & REST API will not work until this deployment finishes. 

  View status: https://{browser_url}/ml/endpoints/{deployment_info.endpoint_name}
  Review App: {deployment_info.rag_app_url}"""
  return message
### END: Ignore this code, temporary workarounds given the Private Preview state of the product

# COMMAND ----------

# MAGIC %run ../RAG_Experimental_Code

# COMMAND ----------



# COMMAND ----------

# MAGIC %md
# MAGIC # Evaluate the chain

# COMMAND ----------

# MAGIC %md
# MAGIC ## First, build an evaluation set
# MAGIC
# MAGIC The evaluation set represents the human-annotated ground truth data.
# MAGIC
# MAGIC | Column Name                  | Type                                              | Required? | Comment                                                                                                                                                  |
# MAGIC |------------------------------|---------------------------------------------------|-----------|----------------------------------------------------------------------------------------------------------------------------------------------------------|
# MAGIC | request_id                   | STRING                                            | Either `request_id` or `request` is required        | Id of the request (question)                                                                                                                             |
# MAGIC | request                     | STRING                                            |   Either `request_id` or `request` is required        | A request (question) to the RAG app, e.g., “What is Spark?”                                                                                              |
# MAGIC | expected_response            | STRING                                            |           | (Optional) The expected answer to this question                                                                                                          |
# MAGIC | expected_retrieval_context   | ARRAY<STRUCT<doc_uri: STRING, content: STRING>>   |           | (Optional) The expected retrieval context. The entries are ordered in descending rank. Each entry can record the URI of the retrieved doc and optionally the (sub)content that was retrieved. |
# MAGIC

# COMMAND ----------

# MAGIC %md
# MAGIC  The eval set is expected to have the following schema:
# MAGIC     - request_id
# MAGIC     - request
# MAGIC     - (optional) expected_response
# MAGIC     - (optional) expected_retrieval_context
# MAGIC     
# MAGIC     The responses to these questions can be provided either through an answer sheet (answer_sheet_table_name)
# MAGIC     or they can be generated by calling into an existing model (`model_uri`).
# MAGIC     Exactly one of these two parameters must be specified.
# MAGIC     
# MAGIC     If an answer sheet is used, then the schema of answer_sheet_table_name is expected to be as follows:
# MAGIC     - request_id
# MAGIC     - app_version
# MAGIC     - (optional) response
# MAGIC     - (optional) retrieval_context

# COMMAND ----------

# DBTITLE 1,Sample Evaluation Dataset Loader
eval_dataset = [
    {
        "request_id": "sample_request_1",
        "request": "What is the purpose of SCE's rate case application?",
        # Expected retrieval context is optional, if not provided, RAG Studio will use LLM judge to assess each retrieved context
        # Expected response is optional
        "expected_response": """The purpose of Southern California Edison Company’s (SCE) rate case application is to request an authorized base revenue requirement (ABRR) of $7.601 billion for the test year 2021, which would reflect an increase in rates to support various objectives. These include maintaining and improving the electric grid, implementing the state’s public policy goals such as wildfire mitigation and de-carbonization through electrification, and adapting to a rapidly modernizing grid. The application also seeks to recover expenditures recorded in various wildfire-related memorandum accounts for 2019 and 20203. Additionally, SCE aims to continue providing safe, reliable, affordable, and increasingly clean electricity to its customers while addressing the challenges posed by the global climate crisis and catastrophic wildfires."""
    },
    {
        "request_id": "sample_request_2",
        "request": "What are different reasons SCE has stated for its request?",
        "expected_response": """The document outlines several reasons for Southern California Edison’s (SCE) request in the General Rate Case Application: Safety and Reliability: SCE emphasizes the need to maintain and improve the grid to ensure safety and reliability for customers, especially in light of the increased risk of catastrophic wildfires.Wildfire Mitigation: The company proposes comprehensive programs and actions aimed at mitigating wildfire risks associated with their equipment due to extreme environmental conditions.Regulatory Compliance: SCE’s request includes necessary expenditures to comply with new regulations and legislative requirements, such as those from Assembly Bill 1054. Clean Energy Goals: SCE is committed to supporting the state’s clean energy policies, including the reduction of greenhouse gas emissions and the integration of distributed energy resources."""
    },
    {
        "request_id": "sample_request_3",
        "request":  "Which regulations affect SCE's expenses?",
        "expected_response": """The document outlines several regulations that impact Southern California Edison Company’s (SCE) expenses: Fire-Threat Safety Map OIR: Regulations for electric power lines in high fire-threat areas, including new inspection, maintenance, and vegetation management regulations. Risk Assessment Mitigation Phase (RAMP): SCE’s RAMP Report examines top safety risks and identifies new mitigations, influencing operational and capital expenditures. Grid Safety & Resiliency Program (GSRP): SCE’s GSRP Application proposes wildfire mitigation programs and activities, impacting costs related to grid hardening. Wildfire Mitigation Plan (WMP): SCE’s WMP describes programs and activities for wildfire risk mitigation, affecting wildfire-related costs. These regulations require SCE to undertake specific actions and programs that contribute to their overall expenses."""
    },
    {
        "request_id": "sample_request_4",
        "request": "Which measures will SCE take to mitigate wildfires?",
        "expected_response": """The document outlines Southern California Edison Company’s (SCE) measures to mitigate wildfires and the associated costs as follows. System Hardening: SCE’s Grid Safety & Resiliency Program (GSRP) and Wildfire Mitigation Program (WMP) include grid resiliency measures like the Wildfire Covered Conductor Program (WCCP) to replace and insulate wires. Situational Awareness: Implementation of high-definition cameras and weather stations to detect and monitor ignitions. Vegetation Management: Expanded programs to increase pruning clearances and remove hazardous trees. Public Outreach and PSPS: Educating customers about wildfire threats and selectively de-energizing lines through the Public Safety Power Shutoff (PSPS) program."""
    },
    {
        "request_id": "sample_request_5",
        "request": "What measures is SCE taking to protect low-income customers from increased electricity costs?",
        "expected_response": """The document outlines SCE’s commitment to affordability, especially for low-income customers, in the context of their General Rate Case (GRC) application. Here are the key points: Affordability Assessment: SCE evaluates the impact of rate increases on all customers, with a particular focus on low-income customers.Four-Part Framework: SCE proposes a framework to assess affordability, which includes evaluating the reasonableness of objectives, scope, pace, and cost, as well as the impact on customers’ ability to pay their bills. Income-Qualified Customers: Special attention is given to income-qualified customers to ensure they are not overburdened by energy expenditures. Policy Compliance: SCE’s efforts align with the state policy that essential electricity should be affordable for all residents. SCE’s approach is to balance the need for infrastructure investments with the importance of keeping electricity affordable for low-income customers."""
    },
    {
        'request_id': 'sample_request_6',
        'request': "How does an electric utility generate electricity?",
        'expected_response': """Though SCE is an electric utility, the question is irrelevant as it addresses all electric utilities and does not directly pertain to why SCE is proposing changes to its electricity rates."""
    },
    {
        'request_id':'sample_request_7',
        'request':"What are major fuel sources for electricity generation?",
        'expected_response':"""This question pertains to the general topic of electricity generation and is directly related to why SCE is proposing changes to its electricity rates."""
    },    
    {
        'request_id':'sample_request_8',
        'request':"How many generating stations does SCE operate?",
        'expected_response':"""This question is not directly related to why SCE is proposing changes to its electricity rates."""
    },
    {
        'request_id':'sample_request_9',
        'request':"How many miles of transmission lines does SCE maintain?",
        'expected_response': """This question is not directly related to why SCE is proposing changes to its electricity rates."""
    },
    {
        'request_id':'sample_request_10',
        'request':"What is the population of the area which SCE services?",
        'expected_response': """This question is not directly related to why SCE is proposing changes to its electricity rates."""
    },
]

responses = [
    {
        'request_id':'sample_request_1',
        'app_version': '1',
        'response':"""The purpose of Southern California Edison Company's (SCE) rate case application is to request the establishment of new rates for the company. The application includes a proposed revenue requirement, a categorization of the proceeding, and a schedule for hearings and issues to be considered. The rate case application is a mechanism for SCE to recover its costs and earn a reasonable return on its investments, while also addressing safety and reliability concerns. The application is aligned with the Commission's modified Rate Case Plan schedule and includes testimony on SCE's corporate safety programs and relevant risk factors."""
    },
    {
        'request_id':'sample_request_2',
        'app_version': '1',
        'response':"""SCE has stated several reasons for its request, including the need to recover costs associated with wildfire mitigation efforts, infrastructure replacement, and ensuring affordable electricity for all residents. The company has also proposed a framework for assessing the affordability of customer rates, which includes considering the benefits of proposed programs, selecting a reasonable and prudent scope and cost, implementing cost-control measures, and evaluating the impact on customers' ability to pay their electric bills."""
    },
    {
        'request_id':'sample_request_3',
        'app_version': '1',
        'response':"""SCE's expenses are affected by regulations from both the CPUC and FERC. In its 2003 GRC, the CPUC adopted SCE's proposed method for splitting costs between those recovered through rates authorized by the CPUC and those authorized by FERC. This method has been followed in SCE's prior GRCs since 2006. Additionally, SCE's expenses include items subject to the ratemaking authority of the FERC."""
    },
    {
        'request_id':'sample_request_4',
        'app_version': '1',
        'response':"""SCE will take several measures to mitigate wildfires. These include system hardening through the Wildfire Covered Conductor Program, improved situational awareness using high-definition cameras and weather stations, expanded inspections and vegetation management programs, and enhanced public outreach and operational practices. SCE will also maintain reasonable insurance coverage to protect customers from third-party wildfire claims and continue to purchase wildfire insurance to ensure that they have the funds necessary to operate the system and serve customers should further utility-related wildfire events occur."""
    },
    {
        'request_id':'sample_request_5',
        'app_version': '1',
        'response':"""SCE assesses affordability when proposing rate increases, considering customer benefits and the impact on customers' ability to pay electric bills, with a special focus on income-qualified customers.
        SCE has a four-part framework for assessing affordability, including evaluating the reasonableness of objectives, selecting a reasonable and prudent scope, pace, and cost, implementing cost-control measures, and considering the impact on customers' ability to pay.
        SCE is committed to maintaining reasonable insurance coverage to protect customers from third-party wildfire claims and ensure the necessary funds to operate the system and serve customers.
        SCE continues to invest in renewable energy resources and zero-carbon resources to supply 100% of all retail sales of electricity to California end-use customers.
        SCE is dedicated to performing crucial functions in a manner that is affordable for customers and is fundamentally committed to spending customer dollars wisely and prudently to provide commensurate value for the important services that they provide."""
    },
    {
        'request_id':'sample_request_6',
        'app_version': '1',
        'response':"""Electric utilities generate electricity through various methods, including burning fossil fuels such as coal or natural gas, harnessing the power of water through hydroelectric dams, using nuclear reactions, or utilizing renewable resources like wind and solar power. The generated electricity is then transmitted and distributed to customers through a network of power lines and substations."""
    },
    {
        'request_id':'sample_request_7',
        'app_version': '1',
        'response':"""The major fuel sources for electricity generation, as mentioned in the context, include fossil fuels, hydro, and solar. The context also mentions Palo Verde, which is a nuclear power plant. However, it's not clear if nuclear power is considered a major fuel source in this context."""
    },
    {
        'request_id':'sample_request_8',
        'app_version': '1',
        'response':"""SCE operates 33 hydroelectric plants, one combined-cycle gas plant with two units, five gas-fired peaker units, a diesel-driven electric generating plant, and 25 solar photovoltaic sites. Additionally, SCE has a 78.21% interest in San Onofre Nuclear Generating Station (SONGS) Units 2 and 3, and a 15.8% interest in Palo Verde Nuclear Generating Station Units 1, 2, and 3."""
    },
    {
        'request_id':'sample_request_9',
        'app_version': '1',
        'response':"""SCE maintains over 4,000 miles of transmission lines."""
    },
    {
        'request_id':'sample_request_10',
        'app_version': '1',
        'response':"""I don't have real-time data access, but based on the provided context, I can't determine the exact population of the area served by Southern California Edison Company (SCE). The context provided is about SCE's earnings, rates, and property, not the population of the service area."""
    }
]


############
# Turn the eval dataset into a Delta Table
############
# TODO: Change these values to your catalog and schema
uc_catalog = "development"
uc_schema = "rag_studio"
eval_table_name = "rate_case_eval_set"
response_table_name = 'rate_case_responses'
eval_table_fqdn = f"{uc_catalog}.{uc_schema}.{eval_table_name}"
response_table_fqdn = f"{uc_catalog}.{uc_schema}.{response_table_name}"

df = spark.read.json(spark.sparkContext.parallelize(eval_dataset))
df.write.format("delta").option("mergeSchema", "true").mode("overwrite").saveAsTable(
    eval_table_fqdn
)
print(f"Eval set written to: {eval_table_fqdn}")

df2 = spark.read.json(spark.sparkContext.parallelize(responses))
df2.write.format("delta").option("mergeSchema", "true").mode("overwrite").saveAsTable(
    response_table_fqdn
)
print(f"Eval set written to: {response_table_fqdn}")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Configure the evaluation
# MAGIC
# MAGIC Databricks provides a set of metrics that enable you to measure the quality, cost and latency of your RAG app. These metrics are curated by Databricks' Research team as the most relevant (no pun intended) metrics for evaluating RAG applications.
# MAGIC
# MAGIC RAG metrics can be computed using either:
# MAGIC 1. Human-labeled ground truth assessments
# MAGIC 2. LLM judge-labeled assessments 
# MAGIC
# MAGIC A subset of the metrics work only with *either* LLM judge-labeled OR human-labeled ground truth asessments.
# MAGIC
# MAGIC ### Improve judge accuracy
# MAGIC
# MAGIC To improve the accuracy of the Databricks judges, you can provide few-shot examples of "good" and "bad" answers for each LLM judge.  Databricks strongly reccomends providing at least 2 postive and 2 negative examples per judge to improve the accuracy.  See the bottom of the notebook [`5_evaluation_without_rag_studio`](M1_Sample_Code/5_evaluation_without_rag_studio.py) for how to do this.  *Note: Even though this example configuration is included in the non-RAG Studio evaluation example, you can use the example configuration with this notebook.*
# MAGIC
# MAGIC
# MAGIC ### Unstructured docs retrieval & generation metrics
# MAGIC
# MAGIC #### Retriever
# MAGIC
# MAGIC RAG Studio supports the following metrics for evaluating the retriever.
# MAGIC
# MAGIC | Question to answer                                                                | Metric | Per trace value | Aggregated value | Work with human assessments | LLM judged assessments & judge name | 
# MAGIC |-----------------------------------------------------------------------------------|--------|--------|--------|------|--------|
# MAGIC | Are the retrieved chunks relevant to the user’s query?                            | Precision of "relevant chunk" @ K | 0 to 100% | 0 to 100% | ✔️ | ✔️ `context_relevant_to_question` |
# MAGIC | Are **ALL** chunks that are relevant to the user’s query retrieved?               | Recall of "relevant chunk" @ K | 0 to 100% |0 to 100% | ✔️ |✖️ |
# MAGIC | Are the retrieved chunks returned in the correct order of most to least relevant? | nDCG of "relevant chunk" @ K | 0 to 1 | 0 to 1 |✔️ | ✖️ |
# MAGIC
# MAGIC #### Generation model
# MAGIC
# MAGIC These metrics measure the generation model's performance when the prompt is augemented with unstructured docs from a retrieval step.
# MAGIC
# MAGIC | Question to answer                                                                | Metric | Per trace value | Aggregated value | Work with human assessments | LLM judged assessments & judge name | 
# MAGIC |-----------------------------------------------------------------------------------|--------|--------|--------|------|--------|
# MAGIC | Is the LLM not hallucinating & responding based ONLY on the context provided? | Faithfulness (to context) | true/false | 0 to 100% | ✖️ | ✔️ `faithful_to_context` |
# MAGIC | Is the response on-topic given the query AND retrieved contexts? | Answer relevance (to query given the context) | true/false | 0 to 100% | ✖️ | ✔️ `relevant_to_question_and_context` | 
# MAGIC | Is the response on-topic given the query? | Answer relevance (to query) | true/false | 0 to 100% | ✖️ | ✔️ `relevant_to_question` | 
# MAGIC | What is the cost of the generation? | Token Count | sum(tokens) | sum(tokens) | n/a |n/a |
# MAGIC | What is the latency of generation? | Latency | milliseconds | average(milliseconds) | n/a | n/a |
# MAGIC
# MAGIC #### RAG chain metrics
# MAGIC
# MAGIC These metrics measure the chain's final response back to the user.  
# MAGIC
# MAGIC | Question to answer                                                                | Metric | Per trace value | Aggregated value | Work with human assessments | LLM judged assessments & judge name | 
# MAGIC |-----------------------------------------------------------------------------------|--------|--------|--------|------|--------|
# MAGIC | Is the response accurate (correct)? | Answer correctness (vs. ground truth) | true/false | 0 to 100% |✔️ `answer_good` | ✖️ |
# MAGIC | Does the response violate any of my company policies (racism, toxicity, etc)? | Toxicity | true/false | 0 to 100% | ✖️ | ✔️ `harmful` |
# MAGIC
# MAGIC

# COMMAND ----------

# DBTITLE 1,YAML Assessment Config Parser
import yaml

config_json = {
    "assessment_judges": [
        {
            "judge_name": "databricks_eval_dbrx",
            "endpoint_name": "endpoints:/databricks-dbrx-instruct",
            "assessments": [
                "relevant_to_question",
                "answer_good"
            ],
        }
    ]
}

config_yml = yaml.dump(config_json)
print(config_yml)

# COMMAND ----------

evaluation_results = rag_eval.evaluate(eval_set_table_name=eval_table_fqdn,answer_sheet_table_name=response_table_fqdn, config=config_yml)

# COMMAND ----------

responses = [
    {
        'request_id':'sample_request_1',
        'app_version': '2',
        'response':"""The purpose of Southern California Edison Company's (SCE) rate case application is to request the establishment of new rates for the company. The application includes a proposed revenue requirement, a categorization of the proceeding, and a schedule for hearings and issues to be considered. The rate case application is a mechanism for SCE to recover its costs and earn a reasonable return on its investments, while also addressing safety and reliability concerns. The application is aligned with the Commission's modified Rate Case Plan schedule and includes testimony on SCE's corporate safety programs and relevant risk factors."""
    },
    {
        'request_id':'sample_request_2',
        'app_version': '2',
        'response':"""SCE has stated several reasons for its request, including the need to recover costs associated with wildfire mitigation efforts, infrastructure replacement, and ensuring affordable electricity for all residents. The company has also proposed a framework for assessing the affordability of customer rates, which includes considering the benefits of proposed programs, selecting a reasonable and prudent scope and cost, implementing cost-control measures, and evaluating the impact on customers' ability to pay their electric bills."""
    },
    {
        'request_id':'sample_request_3',
        'app_version': '2',
        'response':"""SCE's expenses are affected by regulations from both the CPUC and FERC. In its 2003 GRC, the CPUC adopted SCE's proposed method for splitting costs between those recovered through rates authorized by the CPUC and those authorized by FERC. This method has been followed in SCE's prior GRCs since 2006. Additionally, SCE's expenses include items subject to the ratemaking authority of the FERC."""
    },
    {
        'request_id':'sample_request_4',
        'app_version': '2',
        'response':"""SCE will take several measures to mitigate wildfires. These include system hardening through the Wildfire Covered Conductor Program, improved situational awareness using high-definition cameras and weather stations, expanded inspections and vegetation management programs, and enhanced public outreach and operational practices. SCE will also maintain reasonable insurance coverage to protect customers from third-party wildfire claims and continue to purchase wildfire insurance to ensure that they have the funds necessary to operate the system and serve customers should further utility-related wildfire events occur."""
    },
    {
        'request_id':'sample_request_5',
        'app_version': '2',
        'response':"""SCE assesses affordability when proposing rate increases, considering customer benefits and the impact on customers' ability to pay electric bills, with a special focus on income-qualified customers.
        SCE has a four-part framework for assessing affordability, including evaluating the reasonableness of objectives, selecting a reasonable and prudent scope, pace, and cost, implementing cost-control measures, and considering the impact on customers' ability to pay.
        SCE is committed to maintaining reasonable insurance coverage to protect customers from third-party wildfire claims and ensure the necessary funds to operate the system and serve customers.
        SCE continues to invest in renewable energy resources and zero-carbon resources to supply 100% of all retail sales of electricity to California end-use customers.
        SCE is dedicated to performing crucial functions in a manner that is affordable for customers and is fundamentally committed to spending customer dollars wisely and prudently to provide commensurate value for the important services that they provide."""
    },
    {
        'request_id':'sample_request_6',
        'app_version': '2',
        'response':"""Electric utilities generate electricity through various methods, including burning fossil fuels such as coal or natural gas, harnessing the power of water through hydroelectric dams, using nuclear reactions, or utilizing renewable resources like wind and solar power. The generated electricity is then transmitted and distributed to customers through a network of power lines and substations."""
    },
    {
        'request_id':'sample_request_7',
        'app_version': '2',
        'response':"""The major fuel sources for electricity generation, as mentioned in the context, include fossil fuels, hydro, and solar. The context also mentions Palo Verde, which is a nuclear power plant. However, it's not clear if nuclear power is considered a major fuel source in this context."""
    },
    {
        'request_id':'sample_request_8',
        'app_version': '2',
        'response':"""SCE operates 33 hydroelectric plants, one combined-cycle gas plant with two units, five gas-fired peaker units, a diesel-driven electric generating plant, and 25 solar photovoltaic sites. Additionally, SCE has a 78.21% interest in San Onofre Nuclear Generating Station (SONGS) Units 2 and 3, and a 15.8% interest in Palo Verde Nuclear Generating Station Units 1, 2, and 3."""
    },
    {
        'request_id':'sample_request_9',
        'app_version': '2',
        'response':"""SCE maintains over 4,000 miles of transmission lines."""
    },
    {
        'request_id':'sample_request_10',
        'app_version': '2',
        'response':"""I don't have real-time data access, but based on the provided context, I can't determine the exact population of the area served by Southern California Edison Company (SCE). The context provided is about SCE's earnings, rates, and property, not the population of the service area."""
    }
]


############
# Turn the eval dataset into a Delta Table
############
# TODO: Change these values to your catalog and schema
uc_catalog = "development"
uc_schema = "rag_studio"

response_table_name = 'rate_case_responses'

response_table_fqdn = f"{uc_catalog}.{uc_schema}.{response_table_name}"

df2 = spark.read.json(spark.sparkContext.parallelize(responses))
df2.write.format("delta").option("mergeSchema", "true").mode("overwrite").saveAsTable(
    response_table_fqdn
)
print(f"Eval set written to: {response_table_fqdn}")

# COMMAND ----------

config_json_2 = {
    "assessment_judges": [
        {
            # "judge_name": "databricks_eval",
            "judge_name": "databricks_eval_dbrx",
            "endpoint_name": "endpoints:/databricks-dbrx-instruct",
            "assessments": [
                "relevant_to_question",
                {
                    "answer_good": {
                        "examples": [
                            {
                                "request": "What are SCE's wildfire safety measures?",
                                "response": """The document outlines Southern California Edison Company’s (SCE) wildfire safety measures as follows: System Hardening: SCE’s Grid Safety & Resiliency Program (GSRP) and Wildfire Mitigation Program (WMP) include grid resiliency measures, primarily the Wildfire Covered Conductor Program (WCCP), which involves replacing and insulating formerly bare utility wires to reduce ignition risks12. Situational Awareness: SCE is enhancing situational awareness through high-definition cameras and weather stations to detect and monitor potential ignitions, aiming to prevent fire spread3. Inspections and Vegetation Management: SCE has expanded infrastructure inspection programs, such as the Enhanced Overhead Inspection (EOI) program, and increased vegetation management to improve pruning clearances and remove hazardous trees4. Public Outreach and Operational Practices: SCE educates customers about wildfire threats and coordinates with local fire agencies and communities5. During high-risk periods, SCE may proactively de-energize lines through the Public Safety Power Shutoff (PSPS) program6.
                                """,
                                "expected_response": """The document outlines Southern California Edison Company’s (SCE) measures to mitigate wildfires and the associated costs as follows. System Hardening: SCE’s Grid Safety & Resiliency Program (GSRP) and Wildfire Mitigation Program (WMP) include grid resiliency measures like the Wildfire Covered Conductor Program (WCCP) to replace and insulate wires. Situational Awareness: Implementation of high-definition cameras and weather stations to detect and monitor ignitions. Vegetation Management: Expanded programs to increase pruning clearances and remove hazardous trees. Public Outreach and PSPS: Educating customers about wildfire threats and selectively de-energizing lines through the Public Safety Power Shutoff (PSPS) program.""",
                                "value": True,
                                "rationale": "The output details all of the main points covered in the ground truth/expected response",
                            },
                            {
                                "request": "What does SCE stand for?",
                                "response": "South Carolina Electric Company",
                                "expected_response": "Southern California Edison Company",
                                "value": False,
                                "rationale": "The output does not match with the ground truth / expected response.",
                            },
                        ]
                    }
                }
            ],
        }
    ]
}

config_custom_judge_yml = yaml.dump(config_json_2)

# COMMAND ----------

custom_judge_evaluation_results = rag_eval.evaluate(eval_set_table_name=eval_table_fqdn,answer_sheet_table_name=response_table_fqdn, config=config_custom_judge_yml)
