# Databricks notebook source
# MAGIC %md
# MAGIC # Install Dependencies

# COMMAND ----------

# DBTITLE 1,Databricks RAG Studio Installer
# MAGIC %run ../wheel_installer

# COMMAND ----------

dbutils.library.restartPython() 

# COMMAND ----------

# MAGIC %md
# MAGIC # Imports

# COMMAND ----------

import json
import os

import mlflow
from databricks import rag, rag_eval, rag_studio

import html

mlflow.set_registry_uri('databricks-uc')

### START: Ignore this code, temporary workarounds given the Private Preview state of the product
from mlflow.utils import databricks_utils as du
os.environ['MLFLOW_ENABLE_ARTIFACTS_PROGRESS_BAR'] = "false"

def parse_deployment_info(deployment_info):
  browser_url = du.get_browser_hostname()
  message = f"""Deployment of {deployment_info.model_name} version {deployment_info.model_version} initiated.  This can take up to 15 minutes and the Review App & REST API will not work until this deployment finishes. 

  View status: https://{browser_url}/ml/endpoints/{deployment_info.endpoint_name}
  Review App: {deployment_info.rag_app_url}"""
  return message
### END: Ignore this code, temporary workarounds given the Private Preview state of the product

# COMMAND ----------

# MAGIC %run ../RAG_Experimental_Code

# COMMAND ----------

# MAGIC %md
# MAGIC # Evaluate the chain

# COMMAND ----------

# MAGIC %md
# MAGIC ## First, build an evaluation set
# MAGIC
# MAGIC The evaluation set represents the human-annotated ground truth data.
# MAGIC
# MAGIC | Column Name                  | Type                                              | Required? | Comment                                                                                                                                                  |
# MAGIC |------------------------------|---------------------------------------------------|-----------|----------------------------------------------------------------------------------------------------------------------------------------------------------|
# MAGIC | request_id                   | STRING                                            | Either `request_id` or `request` is required        | Id of the request (question)                                                                                                                             |
# MAGIC | request                     | STRING                                            |   Either `request_id` or `request` is required        | A request (question) to the RAG app, e.g., “What is Spark?”                                                                                              |
# MAGIC | expected_response            | STRING                                            |           | (Optional) The expected answer to this question                                                                                                          |
# MAGIC | expected_retrieval_context   | ARRAY<STRUCT<doc_uri: STRING, content: STRING>>   |           | (Optional) The expected retrieval context. The entries are ordered in descending rank. Each entry can record the URI of the retrieved doc and optionally the (sub)content that was retrieved. |
# MAGIC

# COMMAND ----------

# MAGIC %md
# MAGIC  The eval set is expected to have the following schema:
# MAGIC     - request_id
# MAGIC     - request
# MAGIC     - (optional) expected_response
# MAGIC     - (optional) expected_retrieval_context
# MAGIC     
# MAGIC     The responses to these questions can be provided either through an answer sheet (answer_sheet_table_name)
# MAGIC     or they can be generated by calling into an existing model (`model_uri`).
# MAGIC     Exactly one of these two parameters must be specified.
# MAGIC     
# MAGIC     If an answer sheet is used, then the schema of answer_sheet_table_name is expected to be as follows:
# MAGIC     - request_id
# MAGIC     - app_version
# MAGIC     - (optional) response
# MAGIC     - (optional) retrieval_context

# COMMAND ----------

# DBTITLE 1,Sample Evaluation Dataset Loader
eval_dataset = [
    {
        "request_id": "Q1.1",
        "request": "Referring to SCE’s 2021 GRC, what was SCE’s DPT capital forecast, what was authorized, and what was spent? Did SCE use a similar forecasting methodology as in the last case. If no, how did SCE forecast its capital request?",
        # Expected retrieval context is optional, if not provided, RAG Studio will use LLM judge to assess each retrieved context
        # Expected response is optional
        "expected_response": """Please refer to 2025 GRC testimony SCE-06, Vol 1, p. 34 for the 2021 SCE DPT's capital forecast, what was authorized, and what was spent. 
        SCE did use a similar forecasting methodology as in the last case. As stated in the 2021 GRC testimony SCE 6, Vol 2. p. 101, SCE utilized an itemized forecast methodology based on the forecast level of staffing necessary to support the volume of initiatives that will be undertaken in 2021. The 2025 GRC forecast methodology was derived by estimating   the volume of use cases that will be delivered, based on historical delivery velocity, and the number of overall potential use cases. We then applied our Capital and O&M split assumptions for the forecasted use cases to arrive at the capital forecast. Additional details of the calculations are provided in the response for PubAdv-SCE-150-LMW Q.11."""
    },
    {
        "request_id": "Q1.2",
        "request": "Referring to SCE’s 2021 GRC, what was SCE’s DPT capital forecast, what was authorized, and what was spent? Did SCE use a similar forecasting methodology as in the last case. If no, how did SCE forecast its capital request?",
        "expected_response": """Please refer to 2025 GRC testimony SCE-06, Vol 1, p. 34 for the 2021 SCE DPT's capital forecast, what was authorized, and what was spent. 
        SCE did use a similar forecasting methodology as in the last case. As stated in the 2021 GRC testimony SCE 6, Vol 2. p. 101, SCE utilized an itemized forecast methodology based on the forecast level of staffing necessary to support the volume of initiatives that will be undertaken in 2021. The 2025 GRC forecast methodology was derived by estimating   the volume of use cases that will be delivered, based on historical delivery velocity, and the number of overall potential use cases. We then applied our Capital and O&M split assumptions for the forecasted use cases to arrive at the capital forecast. Additional details of the calculations are provided in the response for PubAdv-SCE-150-LMW Q.11."""
    },
    {
        "request_id": "Q1.3",
        "request": "Referring to SCE’s 2021 GRC, what was SCE’s DPT capital forecast, what was authorized, and what was spent? Did SCE use a similar forecasting methodology as in the last case. If no, how did SCE forecast its capital request?",
        "expected_response": """Please refer to 2025 GRC testimony SCE-06, Vol 1, p. 34 for the 2021 SCE DPT's capital forecast, what was authorized, and what was spent. 
        SCE did use a similar forecasting methodology as in the last case. As stated in the 2021 GRC testimony SCE 6, Vol 2. p. 101, SCE utilized an itemized forecast methodology based on the forecast level of staffing necessary to support the volume of initiatives that will be undertaken in 2021. The 2025 GRC forecast methodology was derived by estimating   the volume of use cases that will be delivered, based on historical delivery velocity, and the number of overall potential use cases. We then applied our Capital and O&M split assumptions for the forecasted use cases to arrive at the capital forecast. Additional details of the calculations are provided in the response for PubAdv-SCE-150-LMW Q.11."""
    },
    {
        "request_id": "Q1.4",
        "request": "Referring to SCE’s 2021 GRC, what was SCE’s DPT capital forecast, what was authorized, and what was spent? Did SCE use a similar forecasting methodology as in the last case. If no, how did SCE forecast its capital request?",
        "expected_response": """Please refer to 2025 GRC testimony SCE-06, Vol 1, p. 34 for the 2021 SCE DPT's capital forecast, what was authorized, and what was spent. 
        SCE did use a similar forecasting methodology as in the last case. As stated in the 2021 GRC testimony SCE 6, Vol 2. p. 101, SCE utilized an itemized forecast methodology based on the forecast level of staffing necessary to support the volume of initiatives that will be undertaken in 2021. The 2025 GRC forecast methodology was derived by estimating   the volume of use cases that will be delivered, based on historical delivery velocity, and the number of overall potential use cases. We then applied our Capital and O&M split assumptions for the forecasted use cases to arrive at the capital forecast. Additional details of the calculations are provided in the response for PubAdv-SCE-150-LMW Q.11."""
    },
    {
        "request_id": "Q1.5",
        "request": "Referring to SCE’s 2021 GRC, what was SCE’s DPT capital forecast, what was authorized, and what was spent? Did SCE use a similar forecasting methodology as in the last case. If no, how did SCE forecast its capital request?",
        "expected_response": """Please refer to 2025 GRC testimony SCE-06, Vol 1, p. 34 for the 2021 SCE DPT's capital forecast, what was authorized, and what was spent. 
        SCE did use a similar forecasting methodology as in the last case. As stated in the 2021 GRC testimony SCE 6, Vol 2. p. 101, SCE utilized an itemized forecast methodology based on the forecast level of staffing necessary to support the volume of initiatives that will be undertaken in 2021. The 2025 GRC forecast methodology was derived by estimating   the volume of use cases that will be delivered, based on historical delivery velocity, and the number of overall potential use cases. We then applied our Capital and O&M split assumptions for the forecasted use cases to arrive at the capital forecast. Additional details of the calculations are provided in the response for PubAdv-SCE-150-LMW Q.11."""
    },
    {
        "request_id": "Q2.1",
        "request": "From 2019 to 2022, how much of the DPT’s group recorded capital (presented on SCE-06 Vol.01 workpaper p. 28) applies to joint efforts?",
        "expected_response": """For 2019 to 2022, WorkIt was the only DPT capital cost that recorded to the capitalized software budget."""
    },
    {
        "request_id": "Q2.2",
        "request": "From 2019 to 2022, how much of the DPT’s group recorded capital (presented on SCE-06 Vol.01 workpaper p. 28) applies to joint efforts?",
        "expected_response": """For 2019 to 2022, WorkIt was the only DPT capital cost that recorded to the capitalized software budget."""
    },
    {
        "request_id": "Q2.3",
        "request": "From 2019 to 2022, how much of the DPT’s group recorded capital (presented on SCE-06 Vol.01 workpaper p. 28) applies to joint efforts?",
        "expected_response": """For 2019 to 2022, WorkIt was the only DPT capital cost that recorded to the capitalized software budget."""
    },
    {
        "request_id": "Q2.4",
        "request": "From 2019 to 2022, how much of the DPT’s group recorded capital (presented on SCE-06 Vol.01 workpaper p. 28) applies to joint efforts?",
        "expected_response": """For 2019 to 2022, WorkIt was the only DPT capital cost that recorded to the capitalized software budget."""
    },
    {
        "request_id": "Q3.1",
        "request": "For clarification it does not appear the cumulative benefits outweigh the cumulative spend until 2025. Is this accurate?",
        "expected_response": """That is correct. It is not uncommon for project benefits to lag behind the costs as the investment to develop and implement the solution takes place before the business can realize the benefit from the solution. Benefits can also occur in phases and are dependent on the timing of rollout to end users. Even after rollout, it takes time for end users to be fully trained and to have time to learn the system before full benefits are realized."""
    },
    {
        "request_id": "Q3.2",
        "request": "For clarification it does not appear the cumulative benefits outweigh the cumulative spend until 2025. Is this accurate?",
        "expected_response": """That is correct. It is not uncommon for project benefits to lag behind the costs as the investment to develop and implement the solution takes place before the business can realize the benefit from the solution. Benefits can also occur in phases and are dependent on the timing of rollout to end users. Even after rollout, it takes time for end users to be fully trained and to have time to learn the system before full benefits are realized."""
    },
    {
        "request_id": "Q3.3",
        "request": "For clarification it does not appear the cumulative benefits outweigh the cumulative spend until 2025. Is this accurate?",
        "expected_response": """That is correct. It is not uncommon for project benefits to lag behind the costs as the investment to develop and implement the solution takes place before the business can realize the benefit from the solution. Benefits can also occur in phases and are dependent on the timing of rollout to end users. Even after rollout, it takes time for end users to be fully trained and to have time to learn the system before full benefits are realized."""
    },
    {
        "request_id": "Q3.4",
        "request": "For clarification it does not appear the cumulative benefits outweigh the cumulative spend until 2025. Is this accurate?",
        "expected_response": """That is correct. It is not uncommon for project benefits to lag behind the costs as the investment to develop and implement the solution takes place before the business can realize the benefit from the solution. Benefits can also occur in phases and are dependent on the timing of rollout to end users. Even after rollout, it takes time for end users to be fully trained and to have time to learn the system before full benefits are realized."""
    },
    {
        "request_id": "Q4.1",
        "request": """Why does the continued move to clean energy and SCE’s ongoing commitment to confront climate change require incrementally greater expenditures than in 2022 (2022 Capital Expenditures are $5.822 million compared to over $9 million from 2023 to 2025)?""",
        "expected_response": """The continued move to clean energy and SCE’s ongoing commitment to confront climate change will increase the complexity of our grid systems, generate vast amounts of additional data, demand more advanced analytics algorithms, and require the use of new and emerging technologies to develop digital solutions to meet our clean energy goals. This work necessitates the incremental expenditures requested."""
    },
    {
        "request_id": "Q4.2",
        "request": """Why does the continued move to clean energy and SCE’s ongoing commitment to confront climate change require incrementally greater expenditures than in 2022 (2022 Capital Expenditures are $5.822 million compared to over $9 million from 2023 to 2025)?""",
        "expected_response": """The continued move to clean energy and SCE’s ongoing commitment to confront climate change will increase the complexity of our grid systems, generate vast amounts of additional data, demand more advanced analytics algorithms, and require the use of new and emerging technologies to develop digital solutions to meet our clean energy goals. This work necessitates the incremental expenditures requested."""
    },
    {
        "request_id": "Q4.3",
        "request": """Why does the continued move to clean energy and SCE’s ongoing commitment to confront climate change require incrementally greater expenditures than in 2022 (2022 Capital Expenditures are $5.822 million compared to over $9 million from 2023 to 2025)?""",
        "expected_response": """The continued move to clean energy and SCE’s ongoing commitment to confront climate change will increase the complexity of our grid systems, generate vast amounts of additional data, demand more advanced analytics algorithms, and require the use of new and emerging technologies to develop digital solutions to meet our clean energy goals. This work necessitates the incremental expenditures requested."""
    },
    {
        "request_id": "Q4.4",
        "request": """Why does the continued move to clean energy and SCE’s ongoing commitment to confront climate change require incrementally greater expenditures than in 2022 (2022 Capital Expenditures are $5.822 million compared to over $9 million from 2023 to 2025)?""",
        "expected_response": """The continued move to clean energy and SCE’s ongoing commitment to confront climate change will increase the complexity of our grid systems, generate vast amounts of additional data, demand more advanced analytics algorithms, and require the use of new and emerging technologies to develop digital solutions to meet our clean energy goals. This work necessitates the incremental expenditures requested."""
    },
    {
        "request_id": "Q4.5",
        "request": """Why does the continued move to clean energy and SCE’s ongoing commitment to confront climate change require incrementally greater expenditures than in 2022 (2022 Capital Expenditures are $5.822 million compared to over $9 million from 2023 to 2025)?""",
        "expected_response": """The continued move to clean energy and SCE’s ongoing commitment to confront climate change will increase the complexity of our grid systems, generate vast amounts of additional data, demand more advanced analytics algorithms, and require the use of new and emerging technologies to develop digital solutions to meet our clean energy goals. This work necessitates the incremental expenditures requested."""
    },
    {
        "request_id": "Q5.1",
        "request": """Annually, how much of SCE’s 2023 to 2025 capital forecast applies to the continued move to clean energy and SCE’s ongoing commitment to confront climate change?""",
        "expected_response": """All of SCE's 2023 to 2025 capital forecast is required to improve and transform the way SCE operates, which is required to continue the move to clean energy and enable SCE's ongoing commitment to confront climate change."""
    },
    {
        "request_id": "Q5.2",
        "request": """Annually, how much of SCE’s 2023 to 2025 capital forecast applies to the continued move to clean energy and SCE’s ongoing commitment to confront climate change?""",
        "expected_response": """All of SCE's 2023 to 2025 capital forecast is required to improve and transform the way SCE operates, which is required to continue the move to clean energy and enable SCE's ongoing commitment to confront climate change."""
    },
    {
        "request_id": "Q5.3",
        "request": """Annually, how much of SCE’s 2023 to 2025 capital forecast applies to the continued move to clean energy and SCE’s ongoing commitment to confront climate change?""",
        "expected_response": """All of SCE's 2023 to 2025 capital forecast is required to improve and transform the way SCE operates, which is required to continue the move to clean energy and enable SCE's ongoing commitment to confront climate change."""
    },
    {
        "request_id": "Q6.1",
        "request": """Referring to Testimony p. 26 (lines 4-7) SCE states, “Our goal is to fully utilize data and technology to improve decision making, manage risk proactively, and enhance customer offerings. In pursuit of this goal, SCE will build on the Digital and Process Transformation foundation that has been established over the last few years to further advance operational excellence efforts.” Based on this, please answer the following: Specifically, what operational excellence efforts will be further advanced?""",
        "expected_response": """For examples of operational excellence efforts that have been delivered, please refer to Table IV-3 on page 29-31 in testimony. These are the types of efforts that we expect to be further advanced going forward. """
    },
    {
        "request_id": "Q6.2",
        "request": """Referring to Testimony p. 26 (lines 4-7) SCE states, “Our goal is to fully utilize data and technology to improve decision making, manage risk proactively, and enhance customer offerings. In pursuit of this goal, SCE will build on the Digital and Process Transformation foundation that has been established over the last few years to further advance operational excellence efforts.” Based on this, please answer the following: Specifically, what operational excellence efforts will be further advanced?""",
        "expected_response": """For examples of operational excellence efforts that have been delivered, please refer to Table IV-3 on page 29-31 in testimony. These are the types of efforts that we expect to be further advanced going forward. """
    },
    {
        "request_id": "Q6.3",
        "request": """Referring to Testimony p. 26 (lines 4-7) SCE states, “Our goal is to fully utilize data and technology to improve decision making, manage risk proactively, and enhance customer offerings. In pursuit of this goal, SCE will build on the Digital and Process Transformation foundation that has been established over the last few years to further advance operational excellence efforts.” Based on this, please answer the following: Specifically, what operational excellence efforts will be further advanced?""",
        "expected_response": """For examples of operational excellence efforts that have been delivered, please refer to Table IV-3 on page 29-31 in testimony. These are the types of efforts that we expect to be further advanced going forward. """
    },
    {
        "request_id": "Q6.4",
        "request": """Referring to Testimony p. 26 (lines 4-7) SCE states, “Our goal is to fully utilize data and technology to improve decision making, manage risk proactively, and enhance customer offerings. In pursuit of this goal, SCE will build on the Digital and Process Transformation foundation that has been established over the last few years to further advance operational excellence efforts.” Based on this, please answer the following: Specifically, what operational excellence efforts will be further advanced?""",
        "expected_response": """For examples of operational excellence efforts that have been delivered, please refer to Table IV-3 on page 29-31 in testimony. These are the types of efforts that we expect to be further advanced going forward. """
    },
    {
        "request_id": "Q7.1",
        "request": """In relation to the used and usefulness of prototypes, is SCE asserting that there will be prototypes that will be used and useful? If yes, will those labor costs associated with a prototype that is used and useful be capitalized resulting in the potential for a lower O&M labor cost?""",
        "expected_response": """Yes, SCE is asserting that a portion of the prototypes will be used and useful.   Some of these prototypes may meet capitalization threshold, therefore potentially resulting in a lower O&M labor cost. """
    },
    {
        "request_id": "Q7.2",
        "request": """In relation to the used and usefulness of prototypes, is SCE asserting that there will be prototypes that will be used and useful? If yes, will those labor costs associated with a prototype that is used and useful be capitalized resulting in the potential for a lower O&M labor cost?""",
        "expected_response": """Yes, SCE is asserting that a portion of the prototypes will be used and useful.   Some of these prototypes may meet capitalization threshold, therefore potentially resulting in a lower O&M labor cost. """
    },
    {
        "request_id": "Q7.3",
        "request": """In relation to the used and usefulness of prototypes, is SCE asserting that there will be prototypes that will be used and useful? If yes, will those labor costs associated with a prototype that is used and useful be capitalized resulting in the potential for a lower O&M labor cost?""",
        "expected_response": """Yes, SCE is asserting that a portion of the prototypes will be used and useful.   Some of these prototypes may meet capitalization threshold, therefore potentially resulting in a lower O&M labor cost. """
    },
    {
        "request_id": "Q7.4",
        "request": """In relation to the used and usefulness of prototypes, is SCE asserting that there will be prototypes that will be used and useful? If yes, will those labor costs associated with a prototype that is used and useful be capitalized resulting in the potential for a lower O&M labor cost?""",
        "expected_response": """Yes, SCE is asserting that a portion of the prototypes will be used and useful.   Some of these prototypes may meet capitalization threshold, therefore potentially resulting in a lower O&M labor cost."""
    },
]

# COMMAND ----------

responses = [
    {
        'request_id':'Q1.1',
        'app_version': '1b',
        'response':"""In SCE's 2021 GRC, the DPT capital forecast for 2021-2023 OU software projects was authorized for a portfolio-based forecast of approximately $1.5 million annually. SCE utilized a hybrid forecast approach consisting of an itemized forecast for projects with forecast spending in 2023-2024 and a 2025-2028 portfolio-based forecast based on historical spend within its OU capitalized software portfolio. The forecast for technology solutions was $98,035 million in 2020, $117,677 million in 2021, $129,288 million in 2022, $161,504 million in 2023, $117,883 million in 2024, and a total of $110.86 million for test year 2025. SCE recorded $17.33 million over authorized for 2021 and $28.93 million over authorized for 2022 in OU capitalized software spending. SCE did not use contingency amounts in its forecast for 2025-2028 after the Commission disapproved of this practice in the 2018 GRC."""
    },
    {
        'request_id':'Q1.2',
        'app_version': '1b',
        'response':"""According to Table X-45 in SCE's 2021 GRC, SCE's DPT capitalized software forecast for 2020-2024 was $617 million. However, the authorized amount was not explicitly stated in the given text. As for spending, SCE recorded $98.03 million in 2020 and $117.68 million in 2021 for DPT capitalized software projects. From 2022 to 2024, SCE forecasted spending of $129.29 million, $161.50 million, and $117.88 million respectively. In terms of the forecasting methodology, SCE used a hybrid approach consisting of an itemized forecast for projects with forecast spending in 2023-2024 and a 2025-2028 portfolio-based forecast utilizing historical spend data. SCE notes that this methodology is consistent with Commission practice."""
    },
    {
        'request_id':'Q1.3',
        'app_version': '1b',
        'response':"""According to Table X-45, SCE's forecast for OU capitalized software projects for the 2025 test year is $110.86 million. In the 2021 GRC, SCE was authorized $100.35 million annually for OU capital software projects beginning in 2021, but SCE noted that its spend would increase to $110 million annually beginning in 2022. SCE used a hybrid forecast approach in the 2021 GRC and continued to use it in this case, consisting of an itemized forecast for projects with forecast spending in 2023-2024 and a 2025-2028 portfolio-based forecast comparable to an average of SCE's 2020-2022 recorded costs for other projects. In 2021, SCE recorded $17.33 million over authorized for its OU capitalized software spending, and in 2022, it recorded $28.93 million over authorized spending. SCE notes that changing operational priorities, technological advances, and technical complexities can lead to variances between forecast and recorded costs."""
    },
    {
        'request_id':'Q1.4',
        'app_version': '1b',
        'response':"""In the provided text from the Southern California Edison (SCE) 2021 General Rate Case (GRC) documents, there is specific reference to a Capitalized Software portfolio, which covers several areas including Distribution Inspections & Maintenance and Capital-Related Expense, Transmission Grid, Substation, and Load Growth, Transmission Projects, and Engineering. However, the exact term "DPT" does not appear explicitly within the provided excerpts, and therefore, we cannot precisely determine what "DPT" stands for based on the given information. Nevertheless, SCE's capital forecast for capitalized software and various projects mentioned is described as being developed using an internal cost estimation model that includes industry best practices and SCE subject matter expertise to estimate project cost components. For the Physical Access Control System (PACS) Refresh project (CIT-00-DM-DM-000174), the text includes a table indicating the recorded costs from 2018 to 2022 and forecasts for future years all the way to 2028, totaling $17,049,000 (the values for 2023 to 2028 are not visible in the table provided). Unfortunately, the table does not include the specific data for the 2021 GRC-authorized amount or the original request amount. For the GRC Phase 2 project (CIT-00-DM-DM-000351), another table indicates that there were no recorded costs for 2018 to 2020, and nominal costs of O for 2021 and $3.111 million for 2022, with total recorded/forecast listed as $3.125 million. Again, the 2021 GRC-authorized and original request amounts are not indicated in the table provided. The forecasting methodology described in the text implies a continuation of the hybrid forecast approach that was provided and approved in the 2021 GRC. This approach included a portfolio-based forecast encompassing the 2021-2023 period, without project-level forecasts, thus indicating that specific authorized expenditures for individual projects for 2021 and 2022 were not included.In summary, the SCE's 2021 GRC documents make reference to capital forecasting that utilizes internal cost estimation models based on industry best practices and expertise. However, without the specific data for "DPT" capital forecast, authorized amounts, and actual expenditures, we cannot provide the exact figures for that. Additionally, it appears that SCE continued to use a similar forecasting methodology as in the previous case, which was a portfolio-based approach approved in the 2021 GRC."""
    },
    {
        'request_id':'Q1.5',
        'app_version': '1b',
        'response':"""In 2021, under the General Rate Case (GRC), the Digital & Process Transformation Capital forecast for Southern California Edison (SCE) was authorized at $7.168 million. However, the actual spent amount for the Digital Accelerator (DA) was $5.735 million, which is $1.433 million under the authorized amount. This underspend was attributed to the transfer of funds to the OU Capitalized Software, supporting a joint implementation effort for a critical enterprise solution. Specifically, $3.5 million was transferred from Digital & Process Transformation to Technology Solutions in support of the WorkIt project. Other contributing factors to the underspend include delays in hiring qualified candidates and the reallocation of funds to other higher priority areas within SCE."""
    },
    {
        'request_id':'Q2.1',
        'app_version': '1b',
        'response':"""The information provided does not specify how much of DPT's recorded capital applies to joint efforts."""
    },
    {
        'request_id':'Q2.2',
        'app_version': '1b',
        'response':"""There is no information provided in the given text to answer this question."""
    },
    {
        'request_id':'Q2.3',
        'app_version': '1b',
        'response':"""The given information does not provide a specific answer to this question."""
    },
    {
        'request_id':'Q2.4',
        'app_version': '1b',
        'response':"""To find the amount of the Digital and Process Transformation (DPT) group's recorded capital from 2019 to 2022 that applies to joint efforts, we can look at the relevant figures as presented in the SCE-06 Vol.01 workpaper on page 28. Based on the information provided, the \"Recorded and Forecast Expenditures\" for the years 2019, 2020, 2021, and 2022 from the workpapers summary are: 2019: $3,703, 2020: $4,940, 2021: $5,735, 2022: $5,822. These numbers provide the total recorded capital expenditures for each year but do not specifically indicate how much of this capital was applied to joint efforts. A joint effort or joint project usually refers to an initiative where costs and efforts are shared among multiple entities or partners. Based on the excerpt provided, there is no explicit breakdown or mentions of joint efforts or how the capital is allocated to them within the provided years (2019-2022). To answer the specific question regarding the amount of DPT's recorded capital that applies to joint efforts, we would need additional information or data that details how the funds were allocated to joint projects, if any. Given that this specific information is not presented in the excerpt provided, we are unable to calculate or identify the amount of the DPT’s group recorded capital that applies to joint efforts without further details or an indication of which projects were joint efforts and the specific costs associated with them."""
    },
    {
        'request_id':'Q3.1',
        'app_version': '1b',
        'response':"""Based on the information provided, it appears that the cumulative benefits do not outweigh the cumulative spend until 2025. It is mentioned that the NextGen project will generate operational benefits resulting in avoided cost savings and realized cost savings, and the potential value of these benefits is forecast to be $126.0 million annually, commencing in 2026 and reaching steady state by 2030. However, it is also mentioned that there are additional benefits that are not all-inclusive and some areas of benefits more difficult to determine until the completion of the project."""
    },
    {
        'request_id':'Q3.2',
        'app_version': '1b',
        'response':"""Based on the information provided, it appears that the cumulative benefits of the NextGen ERP project do not outweigh the cumulative spend until 2025. This is supported by the statement in 1.b) (1) that the potential value of the operational benefits resulting in avoided cost savings and realized cost savings is forecast to be $126.0 million annually, commencing in 2026 and reaching steady state by 2030."""
    },
    {
        'request_id':'Q3.3',
        'app_version': '1b',
        'response':"""Based on the information provided, it appears that the cumulative benefits of the NextGen ERP solution implemented by SCE do not outweigh the cumulative spend until 2025. This is because the estimated total cumulative cost savings by 2033 are over $1 billion, but are not all-inclusive and there are some areas of benefits more difficult to determine until the completion of SA2. Additionally, the estimated annual benefits of $126.0 million are projected to commence in 2026 and reach steady state by 2030."""
    },
    {
        'request_id':'Q3.4',
        'app_version': '1b',
        'response':"""Yes, that is accurate. According to the response provided in Q4f: "It is not uncommon for project benefits to lag behind the costs as the investment to develop and implement the solution takes place before the business can realize the benefit from the solution. Benefits can also occur in phases and are dependent on the timing of rollout to end users. Even after rollout, it takes time for end users to be fully trained and to have time to learn the system before full benefits are realized." Hence, the response indicates that the cumulative benefits of the projects and initiatives being discussed are not expected to surpass the cumulative spend until 2025."""
    },
    {
        'request_id':'Q4.1',
        'app_version': '1b',
        'response':"""The continued move to clean energy and SCE's ongoing commitment to confront climate change require incrementally greater expenditures than in 2022 because it will increase the complexity of the grid systems, generate vast amounts of additional data, demand more advanced analytics algorithms, and require the use of new and emerging technologies to develop digital solutions to meet clean energy goals. These investments are necessary to improve and transform the way SCE operates to continue the move to clean energy and enable SCE's ongoing commitment to confront climate change."""
    },
    {
        'request_id':'Q4.2',
        'app_version': '1b',
        'response':"""The continued move to clean energy and SCE's ongoing commitment to confront climate change require incrementally greater expenditures than in 2022 because of increased complexity of grid systems, vast amounts of additional data generation, more advanced analytics algorithms, and the use of new and emerging technologies to develop digital solutions to meet clean energy goals. SCE's investments in technologies, programs, and projects are necessary to clean and modernize the grid, consistent with State (and Federal) clean energy policies and accommodate fast-approaching changes. This work necessitates the incremental expenditures requested."""
    },
    {
        'request_id':'Q4.3',
        'app_version': '1b',
        'response':"""The move to clean energy and SCE's ongoing commitment to confront climate change require incrementally greater expenditures than in 2022 because it will increase the complexity of the grid systems, generate vast amounts of additional data, demand more advanced analytics algorithms, and require the use of new and emerging technologies to develop digital solutions to meet clean energy goals. This work necessitates the incremental expenditures requested. SCE will need to invest in technologies and capabilities to transform the way they operate as a business. The wider changes are spurred by clear State mandates to promote and advance widespread electrification across the economy. SCE must act now to ready the grid for these fast-approaching changes."""
    },
    {
        'request_id':'Q4.4',
        'app_version': '1b',
        'response':"""The continued move to clean energy and SCE's ongoing commitment to confront climate change requires incrementally greater expenditures than in 2022 for a few key reasons: 1. **Complexity of the Grid Systems**: As SCE invests in clean energy initiatives, this results in increased complexity of the electrical grid. The grid requires upgrades to handle a more diverse set of energy sources and to accommodate changes in energy flow, such as the shift from unidirectional energy delivery from centralized power plants to a more distributed and variable set of energy sources (like solar and wind). 2. **Data Management and Advanced Analytics**: The move toward clean energy generates vast amounts of data that must be managed effectively. This includes data from smart meters, distributed energy resources, and other smart grid technologies. Analyzing this data requires sophisticated algorithms and analytics capabilities to optimize grid performance, integrate renewable energy sources efficiently, and predict maintenance and load demands. 3. **New and Emerging Technologies**: As SCE continues to confront climate change, it must invest in new and emerging technologies that support clean energy goals. This can include energy storage systems, advanced control systems for grid management, electric vehicle charging infrastructure, and other technologies that support decarbonization and electrification efforts. 4. **Digital Solutions Development**: Clean energy transformation necessitates SCE to develop digital solutions to manage and optimize its operations and services. This includes investment in IT systems to enhance decision making and manage risks related to the integration of clean energy sources into the grid.\n\n5. **Capital Expenditures for Transformation**: All of IT's 2023 to 2025 capital forecast of approximately $9 million is required to support the transformation needed for SCE to move to clean energy and to confront climate change effectively. This indicates that investments are not only necessary for maintaining current operations but also for transforming the business to meet future challenges and commitments. As SCE moves forward with these initiatives, the capital requirements naturally increase to support the enhanced technical capabilities, infrastructure improvements, and investments in new technologies and processes. The capital expenditures rise from $5.822 million in 2022 to over $9 million each year from 2023 to 2025 to cover these various initiatives aimed at advancing clean energy and climate commitments."""
    },
    {
        'request_id':'Q4.5',
        'app_version': '1b',
        'response':"""Pathway 2045 is Southern California Edison's (SCE) strategic analysis, published in 2019, outlining the necessary actions California must take to meet the state's goal of a clean electrical grid and achieve carbon neutrality by 2045. Pathway 2045 incorporates a comprehensive approach that involves significant electrification, with power supplied by clean energy generation, and is enabled by a major expansion of the electric grid infrastructure.\n\nKey points from Pathway 2045 include:\n\n1. A major increase in utility-scale clean energy resources is needed, primarily from new solar, wind, and energy storage technologies, equating to three times the amount of clean energy online today by 2045.\n\n2. A transition towards electric vehicles (EVs) and electrification of buildings, with 90% of vehicles and 95% of buildings running on electricity by 2045. This will result in an 80% increase in electricity demand.\n\n3. The electric grid will require transformative changes in how it is planned and operated, with state agencies and utilities building out the grid faster than before, including new transmission and distribution projects at rates several times faster than historical trends.\n\n4. Embracing emerging technologies like carbon capture is necessary for achieving feasible solutions and may be essential in sectors where electrification is challenging.\n\n5. Investments in the electric infrastructure will also generate economic benefits and improve air quality. The average SCE customer household is projected to save about 40% on overall annual energy expenses due to reduced fossil fuel use.\n\nIn the context of SCE's General Rate Case (GRC) application A.23-05-010, Pathway 2045 is referenced as the foundational strategy driving SCE's capital forecast and investments in the grid. This includes investments from 2023 to 2025 as the company continues its transition to clean energy and addresses climate change challenges. The investments support both CAPEX (capital expenditures) and O&M (operations and maintenance) costs related to grid modernization, data analytics, advanced technology, and digital solutions to meet the state's decarbonization goals.\n"""
    },
    {
        'request_id':'Q5.1',
        'app_version': '1b',
        'response':"""All of SCE's 2023 to 2025 capital forecast of approximately $9 million applies to the continued move to clean energy and SCE's ongoing commitment to confront climate change."""
    },
    {
        'request_id':'Q5.2',
        'app_version': '1b',
        'response':"""All of SCE's 2023 to 2025 capital forecast of approximately $9 million is required to improve and transform the way SCE operates to continue the move to clean energy and enable SCE's ongoing commitment to confront climate change."""
    },
    {
        'request_id':'Q5.3',
        'app_version': '1b',
        'response':"""According to the response provided to Question 01.c:\n>1c. All of IT's 2023 to 2025 capital forecast of approximately $9 million is required to improve and transform the way SCE operates to continue the move to clean energy and enable SCE's ongoing commitment to confront climate change. So, annually, all of the $9 million capital forecast for 2023 to 2025 applies to SCE's continued move to clean energy and its commitment to confront climate change."""
    },
    {
        'request_id':'Q6.1',
        'app_version': '1b',
        'response':"""The specific operational excellence efforts that will be further advanced by Southern California Edison (SCE) are not explicitly stated in the given information. However, it is mentioned that SCE will build on the Digital and Process Transformation foundation that has been established over the last few years to further advance operational excellence efforts. Examples of operational excellence efforts that have been delivered by SCE in the past can be found in Table IV-3 on page 29-31 of SCE's testimony."""
    },
    {
        'request_id':'Q6.2',
        'app_version': '1b',
        'response':"""The operational excellence efforts that will be further advanced are not specified in the provided text. *However, examples of such efforts that have been delivered in the past can be found in Table IV-3 on page 29-31 of the testimony. These are the types of efforts that SCE expects to further advance in pursuit of their goal to fully utilize data and technology to improve decision making, manage risk proactively, and enhance customer offerings."""
    },
    {
        'request_id':'Q6.3',
        'app_version': '1b',
        'response':"""The specific operational excellence efforts that will be further advanced by SCE in pursuit of their goal to fully utilize data and technology include those listed in Table IV-3 on page 29-31 of their testimony. These efforts include digitizing and improving business processes, achieving end-to-end automation, implementing advanced analytics, and utilizing emerging technologies."""
    },
    {
        'request_id':'Q6.4',
        'app_version': '1b',
        'response':"""In this scenario, the response to the question regarding the operational excellence efforts that will be further advanced by Southern California Edison (SCE) has been guided to be found in Table IV-3 on pages 29-31 of their testimony. Unfortunately, as I am an AI and do not have direct access to SCE's testimony documents, I cannot provide the specifics listed in that table.

        However, generally speaking, advancing operational excellence efforts in a utility company like SCE may include:

        - Further implementation of advanced data analytics to predict and manage energy demands, system maintenance needs, and outage responses more effectively.\n- Enhancing customer digital interfaces to improve the customer service experience, such as developing more intuitive online platforms or mobile apps for customers to manage their accounts and report issues.

        - Adopting more automated processes, including the deployment of robotic process automation (RPA) tools, to streamline internal operations and reduce manual errors and time spent on repetitive tasks.
        - Utilizing emerging technologies such as drones for inspections of electrical infrastructure, which can be safer and more efficient than manual inspections.
        - Investing in advanced metering infrastructure (AMI) to enable real-time energy usage monitoring, which aids in more efficient energy consumption and helps identify system issues more rapidly.
        - Continuously improving cybersecurity measures to protect against threats and to ensure the reliability and security of energy infrastructure and customer data.
        For the exact details of what operational excellence efforts SCE plans to focus on, one would need to refer to the mentioned pages of their testimony or their future strategic documents."""
    },
    {
        'request_id':'Q7.1',
        'app_version': '1b',
        'response':"""The given information does not provide any reference to prototypes being used and capitalized by SCE. Therefore, it cannot be concluded whether or not labor costs associated with a prototype that is used and useful will be capitalized resulting in a potential lower O&M labor cost."""
    },
    {
        'request_id':'Q7.2',
        'app_version': '1b',
        'response':"""The given information does not provide any indication that SCE is asserting the use and usefulness of prototypes or the capitalization of associated labor costs. Therefore, the question cannot be answered based on the given information."""
    },
    {
        'request_id':'Q7.3',
        'app_version': '1b',
        'response':"""The provided information does not mention prototypes and their use or usefulness. Therefore, it cannot be determined if SCE is asserting that there will be prototypes that will be used and useful or if labor costs associated with a prototype that is used and useful will be capitalized resulting in a potential for lower O&M labor cost."""
    },
    {
        'request_id':'Q7.4',
        'app_version': '1b',
        'response':"""Based on the information provided, SCE seems to be stating that some prototyping new technology solutions may not result in creating a \"used and useful\" asset. This suggests that certain prototypes might not reach a stage where they are implemented in a manner that provides ongoing value or is used within SCE's operations or infrastructure. However, the possibility exists that some prototypes will prove to be used and useful. In such cases where the prototype technology solutions are used and useful, the labor costs associated with those successful prototypes could indeed be capitalized. Capitalization refers to the inclusion of the cost as part of the asset's value on the balance sheet rather than being expensed immediately. The capitalization of these costs would therefore mean that they would not immediately affect the O&M (Operations & Maintenance) costs but would be depreciated over the useful life of the capitalized asset instead. This scenario would potentially result in a lower immediate O&M labor cost for SCE since capital expenses are treated differently from O&M expenses and do not immediately appear as costs in the income statement. Instead, they would be amortized or depreciated over the lifespan of the asset, affecting financial statements over a more extended period. In summary, for prototypes that SCE determines to be used and useful, the associated labor costs are likely to be capitalized, leading to potential reductions in immediate O&M labor costs reflected in financial statements."""
    },
]

# COMMAND ----------

############
# Turn the eval dataset into a Delta Table
############
# TODO: Change these values to your catalog and schema
uc_catalog = "development"
uc_schema = "rag_studio"
eval_table_name = "rate_case_eval_set"
response_table_name = 'rate_case_responses'
eval_table_fqdn = f"{uc_catalog}.{uc_schema}.{eval_table_name}"
response_table_fqdn = f"{uc_catalog}.{uc_schema}.{response_table_name}"

df = spark.read.json(spark.sparkContext.parallelize(eval_dataset))
df.write.format("delta").option("mergeSchema", "true").mode("overwrite").saveAsTable(
    eval_table_fqdn
)
print(f"Eval set written to: {eval_table_fqdn}")

df2 = spark.read.json(spark.sparkContext.parallelize(responses))
df2.write.format("delta").option("mergeSchema", "true").mode("overwrite").saveAsTable(
    response_table_fqdn
)
print(f"Eval set written to: {response_table_fqdn}")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Configure the evaluation
# MAGIC
# MAGIC Databricks provides a set of metrics that enable you to measure the quality, cost and latency of your RAG app. These metrics are curated by Databricks' Research team as the most relevant (no pun intended) metrics for evaluating RAG applications.
# MAGIC
# MAGIC RAG metrics can be computed using either:
# MAGIC 1. Human-labeled ground truth assessments
# MAGIC 2. LLM judge-labeled assessments 
# MAGIC
# MAGIC A subset of the metrics work only with *either* LLM judge-labeled OR human-labeled ground truth asessments.
# MAGIC
# MAGIC ### Improve judge accuracy
# MAGIC
# MAGIC To improve the accuracy of the Databricks judges, you can provide few-shot examples of "good" and "bad" answers for each LLM judge.  Databricks strongly reccomends providing at least 2 postive and 2 negative examples per judge to improve the accuracy.  See the bottom of the notebook [`5_evaluation_without_rag_studio`](M1_Sample_Code/5_evaluation_without_rag_studio.py) for how to do this.  *Note: Even though this example configuration is included in the non-RAG Studio evaluation example, you can use the example configuration with this notebook.*
# MAGIC
# MAGIC
# MAGIC ### Unstructured docs retrieval & generation metrics
# MAGIC
# MAGIC #### Retriever
# MAGIC
# MAGIC RAG Studio supports the following metrics for evaluating the retriever.
# MAGIC
# MAGIC | Question to answer                                                                | Metric | Per trace value | Aggregated value | Work with human assessments | LLM judged assessments & judge name | 
# MAGIC |-----------------------------------------------------------------------------------|--------|--------|--------|------|--------|
# MAGIC | Are the retrieved chunks relevant to the user’s query?                            | Precision of "relevant chunk" @ K | 0 to 100% | 0 to 100% | ✔️ | ✔️ `context_relevant_to_question` |
# MAGIC | Are **ALL** chunks that are relevant to the user’s query retrieved?               | Recall of "relevant chunk" @ K | 0 to 100% |0 to 100% | ✔️ |✖️ |
# MAGIC | Are the retrieved chunks returned in the correct order of most to least relevant? | nDCG of "relevant chunk" @ K | 0 to 1 | 0 to 1 |✔️ | ✖️ |
# MAGIC
# MAGIC #### Generation model
# MAGIC
# MAGIC These metrics measure the generation model's performance when the prompt is augemented with unstructured docs from a retrieval step.
# MAGIC
# MAGIC | Question to answer                                                                | Metric | Per trace value | Aggregated value | Work with human assessments | LLM judged assessments & judge name | 
# MAGIC |-----------------------------------------------------------------------------------|--------|--------|--------|------|--------|
# MAGIC | Is the LLM not hallucinating & responding based ONLY on the context provided? | Faithfulness (to context) | true/false | 0 to 100% | ✖️ | ✔️ `faithful_to_context` |
# MAGIC | Is the response on-topic given the query AND retrieved contexts? | Answer relevance (to query given the context) | true/false | 0 to 100% | ✖️ | ✔️ `relevant_to_question_and_context` | 
# MAGIC | Is the response on-topic given the query? | Answer relevance (to query) | true/false | 0 to 100% | ✖️ | ✔️ `relevant_to_question` | 
# MAGIC | What is the cost of the generation? | Token Count | sum(tokens) | sum(tokens) | n/a |n/a |
# MAGIC | What is the latency of generation? | Latency | milliseconds | average(milliseconds) | n/a | n/a |
# MAGIC
# MAGIC #### RAG chain metrics
# MAGIC
# MAGIC These metrics measure the chain's final response back to the user.  
# MAGIC
# MAGIC | Question to answer                                                                | Metric | Per trace value | Aggregated value | Work with human assessments | LLM judged assessments & judge name | 
# MAGIC |-----------------------------------------------------------------------------------|--------|--------|--------|------|--------|
# MAGIC | Is the response accurate (correct)? | Answer correctness (vs. ground truth) | true/false | 0 to 100% |✔️ `answer_good` | ✖️ |
# MAGIC | Does the response violate any of my company policies (racism, toxicity, etc)? | Toxicity | true/false | 0 to 100% | ✖️ | ✔️ `harmful` |
# MAGIC
# MAGIC

# COMMAND ----------

# DBTITLE 1,YAML Assessment Config Parser
import yaml

config_json = {
    "assessment_judges": [
        {
            "judge_name": "databricks_eval_dbrx",
            "endpoint_name": "endpoints:/databricks-dbrx-instruct",
            "assessments": [
                "relevant_to_question",
                "answer_good"
            ],
        }
    ]
}

config_yml = yaml.dump(config_json)
print(config_yml)

# COMMAND ----------

evaluation_results = rag_eval.evaluate(eval_set_table_name=eval_table_fqdn,answer_sheet_table_name=response_table_fqdn, config=config_yml)

# COMMAND ----------

responses = [
    {
        'request_id':'Q1.1',
        'app_version': '2b',
        'response':"""In SCE's 2021 GRC, the DPT capital forecast for 2021-2023 OU software projects was authorized for a portfolio-based forecast of approximately $1.5 million annually. SCE utilized a hybrid forecast approach consisting of an itemized forecast for projects with forecast spending in 2023-2024 and a 2025-2028 portfolio-based forecast based on historical spend within its OU capitalized software portfolio. The forecast for technology solutions was $98,035 million in 2020, $117,677 million in 2021, $129,288 million in 2022, $161,504 million in 2023, $117,883 million in 2024, and a total of $110.86 million for test year 2025. SCE recorded $17.33 million over authorized for 2021 and $28.93 million over authorized for 2022 in OU capitalized software spending. SCE did not use contingency amounts in its forecast for 2025-2028 after the Commission disapproved of this practice in the 2018 GRC."""
    },
    {
        'request_id':'Q1.2',
        'app_version': '2b',
        'response':"""According to Table X-45 in SCE's 2021 GRC, SCE's DPT capitalized software forecast for 2020-2024 was $617 million. However, the authorized amount was not explicitly stated in the given text. As for spending, SCE recorded $98.03 million in 2020 and $117.68 million in 2021 for DPT capitalized software projects. From 2022 to 2024, SCE forecasted spending of $129.29 million, $161.50 million, and $117.88 million respectively. In terms of the forecasting methodology, SCE used a hybrid approach consisting of an itemized forecast for projects with forecast spending in 2023-2024 and a 2025-2028 portfolio-based forecast utilizing historical spend data. SCE notes that this methodology is consistent with Commission practice."""
    },
    {
        'request_id':'Q1.3',
        'app_version': '2b',
        'response':"""According to Table X-45, SCE's forecast for OU capitalized software projects for the 2025 test year is $110.86 million. In the 2021 GRC, SCE was authorized $100.35 million annually for OU capital software projects beginning in 2021, but SCE noted that its spend would increase to $110 million annually beginning in 2022. SCE used a hybrid forecast approach in the 2021 GRC and continued to use it in this case, consisting of an itemized forecast for projects with forecast spending in 2023-2024 and a 2025-2028 portfolio-based forecast comparable to an average of SCE's 2020-2022 recorded costs for other projects. In 2021, SCE recorded $17.33 million over authorized for its OU capitalized software spending, and in 2022, it recorded $28.93 million over authorized spending. SCE notes that changing operational priorities, technological advances, and technical complexities can lead to variances between forecast and recorded costs."""
    },
    {
        'request_id':'Q1.4',
        'app_version': '2b',
        'response':"""In the provided text from the Southern California Edison (SCE) 2021 General Rate Case (GRC) documents, there is specific reference to a Capitalized Software portfolio, which covers several areas including Distribution Inspections & Maintenance and Capital-Related Expense, Transmission Grid, Substation, and Load Growth, Transmission Projects, and Engineering. However, the exact term "DPT" does not appear explicitly within the provided excerpts, and therefore, we cannot precisely determine what "DPT" stands for based on the given information. Nevertheless, SCE's capital forecast for capitalized software and various projects mentioned is described as being developed using an internal cost estimation model that includes industry best practices and SCE subject matter expertise to estimate project cost components. For the Physical Access Control System (PACS) Refresh project (CIT-00-DM-DM-000174), the text includes a table indicating the recorded costs from 2018 to 2022 and forecasts for future years all the way to 2028, totaling $17,049,000 (the values for 2023 to 2028 are not visible in the table provided). Unfortunately, the table does not include the specific data for the 2021 GRC-authorized amount or the original request amount. For the GRC Phase 2 project (CIT-00-DM-DM-000351), another table indicates that there were no recorded costs for 2018 to 2020, and nominal costs of O for 2021 and $3.111 million for 2022, with total recorded/forecast listed as $3.125 million. Again, the 2021 GRC-authorized and original request amounts are not indicated in the table provided. The forecasting methodology described in the text implies a continuation of the hybrid forecast approach that was provided and approved in the 2021 GRC. This approach included a portfolio-based forecast encompassing the 2021-2023 period, without project-level forecasts, thus indicating that specific authorized expenditures for individual projects for 2021 and 2022 were not included.In summary, the SCE's 2021 GRC documents make reference to capital forecasting that utilizes internal cost estimation models based on industry best practices and expertise. However, without the specific data for "DPT" capital forecast, authorized amounts, and actual expenditures, we cannot provide the exact figures for that. Additionally, it appears that SCE continued to use a similar forecasting methodology as in the previous case, which was a portfolio-based approach approved in the 2021 GRC."""
    },
    {
        'request_id':'Q1.5',
        'app_version': '2b',
        'response':"""In 2021, under the General Rate Case (GRC), the Digital & Process Transformation Capital forecast for Southern California Edison (SCE) was authorized at $7.168 million. However, the actual spent amount for the Digital Accelerator (DA) was $5.735 million, which is $1.433 million under the authorized amount. This underspend was attributed to the transfer of funds to the OU Capitalized Software, supporting a joint implementation effort for a critical enterprise solution. Specifically, $3.5 million was transferred from Digital & Process Transformation to Technology Solutions in support of the WorkIt project. Other contributing factors to the underspend include delays in hiring qualified candidates and the reallocation of funds to other higher priority areas within SCE."""
    },
    {
        'request_id':'Q2.1',
        'app_version': '2b',
        'response':"""The information provided does not specify how much of DPT's recorded capital applies to joint efforts."""
    },
    {
        'request_id':'Q2.2',
        'app_version': '2b',
        'response':"""There is no information provided in the given text to answer this question."""
    },
    {
        'request_id':'Q2.3',
        'app_version': '2b',
        'response':"""The given information does not provide a specific answer to this question."""
    },
    {
        'request_id':'Q2.4',
        'app_version': '2b',
        'response':"""To find the amount of the Digital and Process Transformation (DPT) group's recorded capital from 2019 to 2022 that applies to joint efforts, we can look at the relevant figures as presented in the SCE-06 Vol.01 workpaper on page 28. Based on the information provided, the \"Recorded and Forecast Expenditures\" for the years 2019, 2020, 2021, and 2022 from the workpapers summary are: 2019: $3,703, 2020: $4,940, 2021: $5,735, 2022: $5,822. These numbers provide the total recorded capital expenditures for each year but do not specifically indicate how much of this capital was applied to joint efforts. A joint effort or joint project usually refers to an initiative where costs and efforts are shared among multiple entities or partners. Based on the excerpt provided, there is no explicit breakdown or mentions of joint efforts or how the capital is allocated to them within the provided years (2019-2022). To answer the specific question regarding the amount of DPT's recorded capital that applies to joint efforts, we would need additional information or data that details how the funds were allocated to joint projects, if any. Given that this specific information is not presented in the excerpt provided, we are unable to calculate or identify the amount of the DPT’s group recorded capital that applies to joint efforts without further details or an indication of which projects were joint efforts and the specific costs associated with them."""
    },
    {
        'request_id':'Q3.1',
        'app_version': '2b',
        'response':"""Based on the information provided, it appears that the cumulative benefits do not outweigh the cumulative spend until 2025. It is mentioned that the NextGen project will generate operational benefits resulting in avoided cost savings and realized cost savings, and the potential value of these benefits is forecast to be $126.0 million annually, commencing in 2026 and reaching steady state by 2030. However, it is also mentioned that there are additional benefits that are not all-inclusive and some areas of benefits more difficult to determine until the completion of the project."""
    },
    {
        'request_id':'Q3.2',
        'app_version': '2b',
        'response':"""Based on the information provided, it appears that the cumulative benefits of the NextGen ERP project do not outweigh the cumulative spend until 2025. This is supported by the statement in 1.b) (1) that the potential value of the operational benefits resulting in avoided cost savings and realized cost savings is forecast to be $126.0 million annually, commencing in 2026 and reaching steady state by 2030."""
    },
    {
        'request_id':'Q3.3',
        'app_version': '2b',
        'response':"""Based on the information provided, it appears that the cumulative benefits of the NextGen ERP solution implemented by SCE do not outweigh the cumulative spend until 2025. This is because the estimated total cumulative cost savings by 2033 are over $1 billion, but are not all-inclusive and there are some areas of benefits more difficult to determine until the completion of SA2. Additionally, the estimated annual benefits of $126.0 million are projected to commence in 2026 and reach steady state by 2030."""
    },
    {
        'request_id':'Q3.4',
        'app_version': '2b',
        'response':"""Yes, that is accurate. According to the response provided in Q4f: "It is not uncommon for project benefits to lag behind the costs as the investment to develop and implement the solution takes place before the business can realize the benefit from the solution. Benefits can also occur in phases and are dependent on the timing of rollout to end users. Even after rollout, it takes time for end users to be fully trained and to have time to learn the system before full benefits are realized."
        Hence, the response indicates that the cumulative benefits of the projects and initiatives being discussed are not expected to surpass the cumulative spend until 2025."""
    },
    {
        'request_id':'Q4.1',
        'app_version': '2b',
        'response':"""The continued move to clean energy and SCE's ongoing commitment to confront climate change require incrementally greater expenditures than in 2022 because it will increase the complexity of the grid systems, generate vast amounts of additional data, demand more advanced analytics algorithms, and require the use of new and emerging technologies to develop digital solutions to meet clean energy goals. These investments are necessary to improve and transform the way SCE operates to continue the move to clean energy and enable SCE's ongoing commitment to confront climate change."""
    },
    {
        'request_id':'Q4.2',
        'app_version': '2b',
        'response':"""The continued move to clean energy and SCE's ongoing commitment to confront climate change require incrementally greater expenditures than in 2022 because of increased complexity of grid systems, vast amounts of additional data generation, more advanced analytics algorithms, and the use of new and emerging technologies to develop digital solutions to meet clean energy goals. SCE's investments in technologies, programs, and projects are necessary to clean and modernize the grid, consistent with State (and Federal) clean energy policies and accommodate fast-approaching changes. This work necessitates the incremental expenditures requested."""
    },
    {
        'request_id':'Q4.3',
        'app_version': '2b',
        'response':"""The move to clean energy and SCE's ongoing commitment to confront climate change require incrementally greater expenditures than in 2022 because it will increase the complexity of the grid systems, generate vast amounts of additional data, demand more advanced analytics algorithms, and require the use of new and emerging technologies to develop digital solutions to meet clean energy goals. This work necessitates the incremental expenditures requested. SCE will need to invest in technologies and capabilities to transform the way they operate as a business. The wider changes are spurred by clear State mandates to promote and advance widespread electrification across the economy. SCE must act now to ready the grid for these fast-approaching changes."""
    },
    {
        'request_id':'Q4.4',
        'app_version': '2b',
        'response':"""The continued move to clean energy and SCE's ongoing commitment to confront climate change requires incrementally greater expenditures than in 2022 for a few key reasons: 1. **Complexity of the Grid Systems**: As SCE invests in clean energy initiatives, this results in increased complexity of the electrical grid. The grid requires upgrades to handle a more diverse set of energy sources and to accommodate changes in energy flow, such as the shift from unidirectional energy delivery from centralized power plants to a more distributed and variable set of energy sources (like solar and wind). 2. **Data Management and Advanced Analytics**: The move toward clean energy generates vast amounts of data that must be managed effectively. This includes data from smart meters, distributed energy resources, and other smart grid technologies. Analyzing this data requires sophisticated algorithms and analytics capabilities to optimize grid performance, integrate renewable energy sources efficiently, and predict maintenance and load demands. 3. **New and Emerging Technologies**: As SCE continues to confront climate change, it must invest in new and emerging technologies that support clean energy goals. This can include energy storage systems, advanced control systems for grid management, electric vehicle charging infrastructure, and other technologies that support decarbonization and electrification efforts. 4. **Digital Solutions Development**: Clean energy transformation necessitates SCE to develop digital solutions to manage and optimize its operations and services. This includes investment in IT systems to enhance decision making and manage risks related to the integration of clean energy sources into the grid.\n\n5. **Capital Expenditures for Transformation**: All of IT's 2023 to 2025 capital forecast of approximately $9 million is required to support the transformation needed for SCE to move to clean energy and to confront climate change effectively. This indicates that investments are not only necessary for maintaining current operations but also for transforming the business to meet future challenges and commitments. As SCE moves forward with these initiatives, the capital requirements naturally increase to support the enhanced technical capabilities, infrastructure improvements, and investments in new technologies and processes. The capital expenditures rise from $5.822 million in 2022 to over $9 million each year from 2023 to 2025 to cover these various initiatives aimed at advancing clean energy and climate commitments."""
    },
    {
        'request_id':'Q4.5',
        'app_version': '2b',
        'response':"""Pathway 2045 is Southern California Edison's (SCE) strategic analysis, published in 2019, outlining the necessary actions California must take to meet the state's goal of a clean electrical grid and achieve carbon neutrality by 2045. Pathway 2045 incorporates a comprehensive approach that involves significant electrification, with power supplied by clean energy generation, and is enabled by a major expansion of the electric grid infrastructure.\n\nKey points from Pathway 2045 include:\n\n1. A major increase in utility-scale clean energy resources is needed, primarily from new solar, wind, and energy storage technologies, equating to three times the amount of clean energy online today by 2045.\n\n2. A transition towards electric vehicles (EVs) and electrification of buildings, with 90% of vehicles and 95% of buildings running on electricity by 2045. This will result in an 80% increase in electricity demand.\n\n3. The electric grid will require transformative changes in how it is planned and operated, with state agencies and utilities building out the grid faster than before, including new transmission and distribution projects at rates several times faster than historical trends.\n\n4. Embracing emerging technologies like carbon capture is necessary for achieving feasible solutions and may be essential in sectors where electrification is challenging.\n\n5. Investments in the electric infrastructure will also generate economic benefits and improve air quality. The average SCE customer household is projected to save about 40% on overall annual energy expenses due to reduced fossil fuel use.\n\nIn the context of SCE's General Rate Case (GRC) application A.23-05-010, Pathway 2045 is referenced as the foundational strategy driving SCE's capital forecast and investments in the grid. This includes investments from 2023 to 2025 as the company continues its transition to clean energy and addresses climate change challenges. The investments support both CAPEX (capital expenditures) and O&M (operations and maintenance) costs related to grid modernization, data analytics, advanced technology, and digital solutions to meet the state's decarbonization goals.\n"""
    },
    {
        'request_id':'Q5.1',
        'app_version': '2b',
        'response':"""All of SCE's 2023 to 2025 capital forecast of approximately $9 million applies to the continued move to clean energy and SCE's ongoing commitment to confront climate change."""
    },
    {
        'request_id':'Q5.2',
        'app_version': '2b',
        'response':"""All of SCE's 2023 to 2025 capital forecast of approximately $9 million is required to improve and transform the way SCE operates to continue the move to clean energy and enable SCE's ongoing commitment to confront climate change."""
    },
    {
        'request_id':'Q5.3',
        'app_version': '2b',
        'response':"""According to the response provided to Question 01.c:\n>1c. All of IT's 2023 to 2025 capital forecast of approximately $9 million is required to improve and transform the way SCE operates to continue the move to clean energy and enable SCE's ongoing commitment to confront climate change. So, annually, all of the $9 million capital forecast for 2023 to 2025 applies to SCE's continued move to clean energy and its commitment to confront climate change."""
    },
    {
        'request_id':'Q6.1',
        'app_version': '2b',
        'response':"""The specific operational excellence efforts that will be further advanced by Southern California Edison (SCE) are not explicitly stated in the given information. However, it is mentioned that SCE will build on the Digital and Process Transformation foundation that has been established over the last few years to further advance operational excellence efforts. Examples of operational excellence efforts that have been delivered by SCE in the past can be found in Table IV-3 on page 29-31 of SCE's testimony."""
    },
    {
        'request_id':'Q6.2',
        'app_version': '2b',
        'response':"""The operational excellence efforts that will be further advanced are not specified in the provided text. *However, examples of such efforts that have been delivered in the past can be found in Table IV-3 on page 29-31 of the testimony. These are the types of efforts that SCE expects to further advance in pursuit of their goal to fully utilize data and technology to improve decision making, manage risk proactively, and enhance customer offerings."""
    },
    {
        'request_id':'Q6.3',
        'app_version': '2b',
        'response':"""The specific operational excellence efforts that will be further advanced by SCE in pursuit of their goal to fully utilize data and technology include those listed in Table IV-3 on page 29-31 of their testimony. These efforts include digitizing and improving business processes, achieving end-to-end automation, implementing advanced analytics, and utilizing emerging technologies."""
    },
    {
        'request_id':'Q6.4',
        'app_version': '2b',
        'response':"""In this scenario, the response to the question regarding the operational excellence efforts that will be further advanced by Southern California Edison (SCE) has been guided to be found in Table IV-3 on pages 29-31 of their testimony. Unfortunately, as I am an AI and do not have direct access to SCE's testimony documents, I cannot provide the specifics listed in that table.

        However, generally speaking, advancing operational excellence efforts in a utility company like SCE may include:

        - Further implementation of advanced data analytics to predict and manage energy demands, system maintenance needs, and outage responses more effectively.\n- Enhancing customer digital interfaces to improve the customer service experience, such as developing more intuitive online platforms or mobile apps for customers to manage their accounts and report issues.

        - Adopting more automated processes, including the deployment of robotic process automation (RPA) tools, to streamline internal operations and reduce manual errors and time spent on repetitive tasks.
        - Utilizing emerging technologies such as drones for inspections of electrical infrastructure, which can be safer and more efficient than manual inspections.
        - Investing in advanced metering infrastructure (AMI) to enable real-time energy usage monitoring, which aids in more efficient energy consumption and helps identify system issues more rapidly.
        - Continuously improving cybersecurity measures to protect against threats and to ensure the reliability and security of energy infrastructure and customer data.
        For the exact details of what operational excellence efforts SCE plans to focus on, one would need to refer to the mentioned pages of their testimony or their future strategic documents."""
    },
    {
        'request_id':'Q7.1',
        'app_version': '2b',
        'response':"""The given information does not provide any reference to prototypes being used and capitalized by SCE. Therefore, it cannot be concluded whether or not labor costs associated with a prototype that is used and useful will be capitalized resulting in a potential lower O&M labor cost."""
    },
    {
        'request_id':'Q7.2',
        'app_version': '2b',
        'response':"""The given information does not provide any indication that SCE is asserting the use and usefulness of prototypes or the capitalization of associated labor costs. Therefore, the question cannot be answered based on the given information."""
    },
    {
        'request_id':'Q7.3',
        'app_version': '2b',
        'response':"""The provided information does not mention prototypes and their use or usefulness. Therefore, it cannot be determined if SCE is asserting that there will be prototypes that will be used and useful or if labor costs associated with a prototype that is used and useful will be capitalized resulting in a potential for lower O&M labor cost."""
    },
    {
        'request_id':'Q7.4',
        'app_version': '2b',
        'response':"""Based on the information provided, SCE seems to be stating that some prototyping new technology solutions may not result in creating a \"used and useful\" asset. This suggests that certain prototypes might not reach a stage where they are implemented in a manner that provides ongoing value or is used within SCE's operations or infrastructure. However, the possibility exists that some prototypes will prove to be used and useful. In such cases where the prototype technology solutions are used and useful, the labor costs associated with those successful prototypes could indeed be capitalized. Capitalization refers to the inclusion of the cost as part of the asset's value on the balance sheet rather than being expensed immediately. The capitalization of these costs would therefore mean that they would not immediately affect the O&M (Operations & Maintenance) costs but would be depreciated over the useful life of the capitalized asset instead. This scenario would potentially result in a lower immediate O&M labor cost for SCE since capital expenses are treated differently from O&M expenses and do not immediately appear as costs in the income statement. Instead, they would be amortized or depreciated over the lifespan of the asset, affecting financial statements over a more extended period. In summary, for prototypes that SCE determines to be used and useful, the associated labor costs are likely to be capitalized, leading to potential reductions in immediate O&M labor costs reflected in financial statements."""
    },
]

# COMMAND ----------

############
# Turn the eval dataset into a Delta Table
############
# TODO: Change these values to your catalog and schema
uc_catalog = "development"
uc_schema = "rag_studio"

response_table_name = 'rate_case_responses'

response_table_fqdn = f"{uc_catalog}.{uc_schema}.{response_table_name}"

df2 = spark.read.json(spark.sparkContext.parallelize(responses))
df2.write.format("delta").option("mergeSchema", "true").mode("overwrite").saveAsTable(
    response_table_fqdn
)
print(f"Eval set written to: {response_table_fqdn}")

# COMMAND ----------

config_json_2 = {
    "assessment_judges": [
        {
            # "judge_name": "databricks_eval",
            "judge_name": "databricks_eval_dbrx",
            "endpoint_name": "endpoints:/databricks-dbrx-instruct",
            "assessments": [
                "relevant_to_question",
                {
                    "answer_good": {
                        "examples": [
                            {
                                "request": "What are SCE's wildfire safety measures?",
                                "response": """The document outlines Southern California Edison Company’s (SCE) wildfire safety measures as follows: System Hardening: SCE’s Grid Safety & Resiliency Program (GSRP) and Wildfire Mitigation Program (WMP) include grid resiliency measures, primarily the Wildfire Covered Conductor Program (WCCP), which involves replacing and insulating formerly bare utility wires to reduce ignition risks12. Situational Awareness: SCE is enhancing situational awareness through high-definition cameras and weather stations to detect and monitor potential ignitions, aiming to prevent fire spread3. Inspections and Vegetation Management: SCE has expanded infrastructure inspection programs, such as the Enhanced Overhead Inspection (EOI) program, and increased vegetation management to improve pruning clearances and remove hazardous trees4. Public Outreach and Operational Practices: SCE educates customers about wildfire threats and coordinates with local fire agencies and communities5. During high-risk periods, SCE may proactively de-energize lines through the Public Safety Power Shutoff (PSPS) program6.
                                """,
                                "expected_response": """The document outlines Southern California Edison Company’s (SCE) measures to mitigate wildfires and the associated costs as follows. System Hardening: SCE’s Grid Safety & Resiliency Program (GSRP) and Wildfire Mitigation Program (WMP) include grid resiliency measures like the Wildfire Covered Conductor Program (WCCP) to replace and insulate wires. Situational Awareness: Implementation of high-definition cameras and weather stations to detect and monitor ignitions. Vegetation Management: Expanded programs to increase pruning clearances and remove hazardous trees. Public Outreach and PSPS: Educating customers about wildfire threats and selectively de-energizing lines through the Public Safety Power Shutoff (PSPS) program.""",
                                "value": True,
                                "rationale": "The output details all of the main points covered in the ground truth/expected response",
                            },
                            {
                                "request": "What does SCE stand for?",
                                "response": "South Carolina Electric Company",
                                "expected_response": "Southern California Edison Company",
                                "value": False,
                                "rationale": "The output does not match with the ground truth / expected response.",
                            },
                        ]
                    }
                }
            ],
        }
    ]
}

config_custom_judge_yml = yaml.dump(config_json_2)

# COMMAND ----------

custom_judge_evaluation_results = rag_eval.evaluate(eval_set_table_name=eval_table_fqdn,answer_sheet_table_name=response_table_fqdn, config=config_custom_judge_yml)

# COMMAND ----------


